default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000
  host: 127.0.0.1

development:
  <<: *default
  database: MessageApp

test:
  <<: *default
  database: MessageApp_test

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
